[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"
  config.schedule = "* * * * *"  # This cron expression runs every minute
